.tests:
  script: pushd /var/tmp && popd && pip3 install -e . && LDAPNOINIT=1 LDAP0_TRACE_LEVEL=3 coverage3 run setup.py test && coverage3 report
  stage: test
  only:
    refs:
      - branches

.LTB-RPM-REPO: &script-1 |
  echo '
  [ltb-project]
  name=LTB project packages
  baseurl=https://ltb-project.org/rpm/$releasever/$basearch
  enabled=1
  gpgcheck=1
  gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-LTB-project
  ' > /etc/yum.repos.d/ltb-project.repo


test:tumbleweed:
  extends: .tests
  image: opensuse/tumbleweed
  before_script:
  - zypper --non-interactive dist-upgrade --no-recommends
  - zypper --non-interactive install --no-recommends --auto-agree-with-licenses --no-recommends cyrus-sasl-digestmd5 cyrus-sasl-scram cyrus-sasl-crammd5 cyrus-sasl-plain openldap2 python3 python3-pyasn1-modules python3-setuptools python3-setuptools-git python3-setuptools_scm gcc python3-devel openldap2-devel cyrus-sasl-devel python3-pip openldap2-back-sock openldap2-contrib openldap2-client
  - 'echo "mech_list: PLAIN DIGEST-MD5 CRAM-MD5 SCRAM-SHA-1 EXTERNAL" > /etc/sasl2/slapd.conf'
  - pip3 install coverage

test:leap:
  extends: .tests
  image: opensuse/leap
  before_script:
  - zypper --non-interactive update --no-recommends
  - zypper --non-interactive install --no-recommends --auto-agree-with-licenses --no-recommends cyrus-sasl-digestmd5 cyrus-sasl-scram cyrus-sasl-crammd5 cyrus-sasl-plain openldap2 python3 python3-pyasn1-modules python3-setuptools python3-setuptools-git python3-setuptools_scm gcc python3-devel openldap2-devel cyrus-sasl-devel python3-pip openldap2-back-sock openldap2-contrib openldap2-client
  - 'echo "mech_list: PLAIN DIGEST-MD5 CRAM-MD5 SCRAM-SHA-1 EXTERNAL" > /etc/sasl2/slapd.conf'
  - pip3 install coverage

test:centos7:
  extends: .tests
  image: centos:7
  before_script:
  - yum update -y
  - rpm --import https://ltb-project.org/lib/RPM-GPG-KEY-LTB-project
  - yum install -y epel-release
  - *script-1
  - yum install -y cyrus-sasl-md5 cyrus-sasl-plain cyrus-sasl-scram openldap-ltb openldap-ltb-contrib-overlays openldap-ltb-mdb-utils openldap-ltb-ppm openldap-devel gcc cyrus-sasl-devel python36 python36-devel python36-setuptools python36-pip
  - 'echo "mech_list: PLAIN DIGEST-MD5 CRAM-MD5 SCRAM-SHA-1 EXTERNAL" > /etc/sasl2/slapd.conf'
  - pip3 install coverage
  - export SLAPD=/usr/local/openldap/libexec/slapd
  - export SCHEMA=/usr/local/openldap/etc/openldap/schema
  - export BIN=/usr/local/openldap/bin
  - export SBIN=/usr/local/openldap/sbin

test:debian:
  extends: .tests
  image: debian:latest
  before_script:
  - apt-get update
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get install --yes --quiet --no-install-recommends --option 'DPkg::Options=--force-confold' --option 'DPkg::Options=--force-confdef' slapd ldap-utils libldap2-dev libsasl2-dev libsasl2-modules python3-setuptools python3-setuptools-git python3-setuptools-scm gcc python3-dev python3-pip
  - mkdir /etc/sasl2
  - 'echo "mech_list: PLAIN DIGEST-MD5 CRAM-MD5 SCRAM-SHA-1 EXTERNAL" > /etc/sasl2/slapd.conf'
  - pip3 install coverage
  - export SLAPD=/usr/sbin/slapd
  - export SCHEMA=/etc/ldap/schema
  - export BIN=/usr/bin
  - export SBIN=/usr/sbin
